learning_rate: 1e-4
beta1: 0.9
beta2: 0.9
in_channels: 4
channels: 256
patch_factor: 16
patch_blocks: 1
resnet_groups: 8
kernel_multiplier_downsample: 2
kernel_sizes_init:
  - 1
  - 3
  - 7
multipliers:
  - 1
  - 2
  - 4
  - 4
  - 4
  - 4
  - 4
factors:
  - 4
  - 4
  - 4
  - 2
  - 2
  - 2
num_blocks:
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
attentions:
  - false
  - false
  - false
  - true
  - true
  - true
attention_heads: 8
attention_features: 128
attention_multiplier: 2
use_nearest_upsample: false
use_skip_scale: true
use_attention_bottleneck: true
diffusion_sigma_distribution_mean: -3.0
diffusion_sigma_distribution_std: 1.0
# diffusion_sigma_distribution: LogNormalDistribution(mean=-3.0, std=1.0)
diffusion_sigma_data: 0.2
diffusion_dynamic_threshold: 0.0
# batch_size: 8
batch_size: 1
num_workers: 4
pin_memory: true