[tool.poetry]
name = "pipelines"
version = "0.1.0"
description = ""
authors = ["Adam Gorski <adamsebastiangorski@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
kedro = "^0.18.9"
dagshub = "^0.2.17.post1"
dvc = "^2.58.2"
mlflow = "^2.3.2"
poethepoet = "^0.20.0"
soundfile = "^0.12.1"
museval = "^0.4.1"
mir-eval = "^0.7"
openunmix = "^1.2.1"
scipy = "^1.10.1"
norbert = "^0.2.1"
asteroid = "^0.6.0"
kedro-viz = "^6.2.0"
requests = "^2.31.0"
kedro-datasets = "^1.4.0"
musdb = "^0.4.0"
stempeg = "^0.2.3"
ffmpeg = "^1.4"
ffprobe = "0.5"
jupyter = "^1.0.0"
torchaudio = "^2.0.2"
ffmpeg-python = "0.2.0"
librosa = "^0.10.0.post2"
tqdm = "^4.65.0"
transformers = "^4.30.1"
statsmodels = "^0.14.0"
pywavelets = "^1.4.1"
datasets = "^2.13.0"
h5py = "^3.9.0"
resampy = "^0.4.2"
matplotlib = "^3.7.2"
tensorboard = "^2.13.0"
julius = "^0.2.7"
torchvision = "^0.15.2"
tables = "^3.8.0"
python-dotenv = "^1.0.0"
lightning = "^2.0.5"
autopep8 = "^2.0.2"
isort = "^5.12.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
poethepoet = "^0.20.0"

[tool.poe.tasks]
force-cuda11 = "python -m pip install torch==2.0.1+cu117 -f https://download.pytorch.org/whl/torch_stable.html"
